feat: check if nft exists once selected for transfer
matter-labs/zksync-wallet-vue pull request #164
Opened 2021-11-12 18:46 UTC by JackHamer09

2021-11-16 17:29 UTC, keriat requested changes
Slight change requested

2021-11-16 17:29 UTC, keriat commented on src/blocks/Transaction.vue
> +          <loader v-if="allowanceLoading || (!nftExists && nftExistsLoading) || buttonLoader || requestingSigner" class="_margin-left-1" size="xs" />
Move it to the computed property plz

2021-11-16 17:29 UTC, keriat commented on src/blocks/Transaction.vue
> +          <loader v-if="allowanceLoading || (!nftExists && nftExistsLoading) || buttonLoader || requestingSigner" class="_margin-left-1" size="xs" />
Single one I mean

2021-11-16 23:16 UTC, keriat requested changes
Minor changes requested

2021-11-16 23:16 UTC, keriat commented on src/blocks/Transaction.vue
> +      <div v-if="chosenToken && mainToken === 'L2-NFT' && !nftExists && !nftExistsLoading" class="errorText _text-center _margin-top-1">
Implode it into computed property. This should be done any time you're using more then 2 conditions directly in the code

2021-11-16 23:16 UTC, keriat commented on src/blocks/Transaction.vue
> +    if (!this.$store.getters["zk-account/loggedIn"]) {
Shouldn't this check be moved to the middleware?

2021-11-17 15:01 UTC, AnastasiiaVashchuk approved these changes

2021-11-17 18:40 UTC, keriat approved these changes
LGTM

2021-11-17 18:40 UTC, merged

2022-01-04 10:06 UTC, keriat commented
:tada: This PR is included in version 2.7.0 :tada:

The release is available on [GitHub release](https://github.com/matter-labs/zksync-wallet-vue/releases/tag/2.7.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: