feat: add env property to mixpanel
matter-labs/zksync-wallet-vue pull request #200
Opened 2021-12-22 10:18 UTC by andriidrebot

2021-12-22 12:22 UTC, JackHamer09 approved these changes

2021-12-22 12:38 UTC, keriat requested changes
I propose to wrap up whole analytics into the plugin and leave a single (or a couple) external super-dummy methods to tract something. Allow access to this method(s) by registering globally with Vue.use.

Do the same with the network switching.

Maybe (not pushing this exactly) do it as a lazy-plugin for the core module. Has trade offs so it's the matter of discussion.

2021-12-22 12:38 UTC, keriat commented on src/layouts/index.vue
> +  computed: {
IMO, there is no sense to wrap up getter into the computed property. In that case you trade up extra reactive listener for a something like readability which actually don't effect the code

2021-12-22 12:38 UTC, keriat commented on src/layouts/index.vue
> +  watch: {
...and the watcher, again, IMO, doesn't belong here: when u change the network it's not a state mutation, it's a trigger to cast sequence of actions, including the logout, redirection, re-login etc.

To maintain solidity of an architecture I propose u to:
- add global call though the one-time registration ``` Vue.use()``` of a single method like track() 
- move everything caused by the network switching trigger into a single method
- compose analytics itself into a reusable plugin;
— do the same for the network switcher.

**PROs**
- one place to change in need;
- reusable code;
- keeping logic away from the UI and from the data-processors/controllers)

2021-12-23 12:22 UTC, keriat approved these changes

2021-12-23 13:27 UTC, merged

2022-01-04 10:05 UTC, keriat commented
:tada: This PR is included in version 2.7.0 :tada:

The release is available on [GitHub release](https://github.com/matter-labs/zksync-wallet-vue/releases/tag/2.7.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: